### PR TITLE
Adding 3gp support for Firefox Reality's speech interface (and also updating node packages)

### PR DESCRIPTION
**Pull request by andrenatal**
@g-k r? 

```
anatal-35389:speech-proxy anatal$ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 483 scanned packages
```

### CODE REVIEW

**Comment by andrenatal** [comment]
Hi @g-k and @milescrabill! 

We are adding a speech interface to Firefox Reality and we need speech-proxy to start supporting 3gpp as well. Could you please review this and merge into staging, please?

**Comment by andrenatal** [comment]
Thanks @g-k . 

@milescrabill if this lgty, how easy is to deploy to staging?

**Comment by milescrabill** [comment]
LGTM. Once merged, ideally a docker image will be built and pushed via circleci to https://hub.docker.com/r/mozilla/speaktome/.

From there, it's easy to deploy to stage.

**Comment by andrenatal** [comment]
Thanks @milescrabill. I just merged it!

**Pull request merged**
